[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
cache_path  = "forge-cache"
evm_version = "london"
solc = "0.8.24"
optimizer_runs = 999_999

[fuzz]
runs = 1_000

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
